export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userContants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const projectConstansts = {
  GET_ALL_PROJECT_REQUEST: "GET_ALL_PROJECT_REQUEST",
  GET_ALL_PROJECT_SUCCESS: "GET_ALL_PROJECT_SUCCESS",
  GET_ALL_PROJECT_FAILURE: "GET_ALL_PROJECT_FAILURE",
  ADD_NEW_PROJECT_REQUEST: "ADD_NEW_PROJECT_REQUEST",
  ADD_NEW_PROJECT_SUCCESS: "ADD_NEW_PROJECT_SUCCESS",
  ADD_NEW_PROJECT_FAILURE: "ADD_NEW_PROJECT_FAILURE",
  UPDATE_PROJECT_REQUEST: "UPDATE_PROJECT_REQUEST",
  UPDATE_PROJECT_SUCCESS: "UPDATE_PROJECT_SUCCESS",
  UPDATE_PROJECT_FAILURE: "UPDATE_PROJECT_FAILURE",
  DELETE_PROJECT_REQUEST: "DELETE_PROJECT_REQUEST",
  DELETE_PROJECT_SUCCESS: "DELETE_PROJECT_SUCCESS",
  DELETE_PROJECT_FAILURE: "DELETE_PROJECT_FAILURE",
};

export const masterConstansts = {
  GET_ALL_MASTER_REQUEST: "GET_ALL_MASTER_REQUEST",
  GET_ALL_MASTER_SUCCESS: "GET_ALL_MASTER_SUCCESS",
  GET_ALL_MASTER_FAILURE: "GET_ALL_MASTER_FAILURE",
  ADD_NEW_MASTER_REQUEST: "ADD_NEW_MASTER_REQUEST",
  ADD_NEW_MASTER_SUCCESS: "ADD_NEW_MASTER_SUCCESS",
  ADD_NEW_MASTER_FAILURE: "ADD_NEW_MASTER_FAILURE",
  UPDATE_MASTER_REQUEST: "UPDATE_MASTER_REQUEST",
  UPDATE_MASTER_SUCCESS: "UPDATE_MASTER_SUCCESS",
  UPDATE_MASTER_FAILURE: "UPDATE_MASTER_FAILURE",
  DELETE_MASTER_REQUEST: "DELETE_MASTER_REQUEST",
  DELETE_MASTER_SUCCESS: "DELETE_MASTER_SUCCESS",
  DELETE_MASTER_FAILURE: "DELETE_MASTER_FAILURE",
};

export const propertyConstansts = {
  GET_ALL_PROPERTY_REQUEST: "GET_ALL_PROPERTY_REQUEST",
  GET_ALL_PROPERTY_SUCCESS: "GET_ALL_PROPERTY_SUCCESS",
  GET_ALL_PROPERTY_FAILURE: "GET_ALL_PROPERTY_FAILURE",
};

export const unitConstants = {
  GET_ALL_UNITS_REQUEST: "GET_ALL_UNITS_REQUEST",
  GET_ALL_UNITS_SUCCESS: "GET_ALL_UNITS_SUCCESS",
  GET_ALL_UNITS_FAILURE: "GET_ALL_UNITS_FAILURE",

  DELETE_UNIT_BY_ID_REQUEST: "DELETE_UNIT_BY_ID_REQUEST",
  DELETE_UNIT_BY_ID_SUCCESS: "DELETE_UNIT_BY_ID_SUCCESS",
  DELETE_UNIT_BY_ID_FAILURE: "DELETE_UNIT_BY_ID_FAILURE",

  ADD_UNIT_REQUEST: "ADD_UNIT_REQUEST",
  ADD_UNIT_SUCCESS: "ADD_UNIT_REQUEST",
  ADD_UNIT_FAILURE: "ADD_UNIT_FAILURE",
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const initialUnitConstants = {
  GET_ALL_INITIAL_UNITS_REQUEST: "GET_ALL_INITIAL_UNITS_REQUEST",
  GET_ALL_INITIAL_UNITS_SUCCESS: "GET_ALL_INITIAL_UNITS_SUCCESS",
  GET_ALL_INITIAL_UNITS_FAILURE: "GET_ALL_INITIAL_UNITS_FAILURE",
};
